name: Build

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm i
      - run: npm run build
      - run: zip -rj atarashii-${{ steps.package-version.outputs.current-version }}.zip build/
      - name: Create Release
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: atarashii-${{ steps.package-version.outputs.current-version }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
