name: Build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build extension
        run: npm run build

      - name: Zip release artifact
        run: zip -rj atarashii-${{ steps.package-version.outputs.current-version }}.zip dist/

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: atarashii-${{ steps.package-version.outputs.current-version }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
