name: Build & Draft Release

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm i
      - run: npm run build
      - run: zip -rj atarashii-${{ steps.package-version.outputs.current-version }}.zip build/
      - uses: release-drafter/release-drafter@v5